name: "Deploy to NuGet"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 'build, pack & publish'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: 'Publish package'
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: ExceptionAll/ExceptionAll.csproj
        NUGET_KEY: ${{ secrets.NUGET_AUTH_TOKEN }}