name: "Deploy to NuGet"

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: 'build, pack & publish'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: 'Publish Abstractions'
      id : publish_abstractions_nuget
      uses: alirezanet/publish-nuget@v3.0.4
      with:
        PROJECT_FILE_PATH: src/ExceptionAll.Abstractions/ExceptionAll.Abstractions.csproj
        NUGET_KEY: ${{ secrets.NUGET_AUTH_TOKEN }}
        INCLUDE_SYMBOLS: true
        
    - name: 'Publish ExceptionAll'
      id: publish_exceptionall_nuget
      uses: alirezanet/publish-nuget@v3.0.4
      with:
        PROJECT_FILE_PATH: src/ExceptionAll/ExceptionAll.csproj
        NUGET_KEY: ${{ secrets.NUGET_AUTH_TOKEN }}
        INCLUDE_SYMBOLS: true

    - name: 'Publish Client'
      id: publish_client_nuget
      uses: alirezanet/publish-nuget@v3.0.4
      with:
        PROJECT_FILE_PATH: src/ExceptionAll.Client/ExceptionAll.Client.csproj
        NUGET_KEY: ${{ secrets.NUGET_AUTH_TOKEN }}
        INCLUDE_SYMBOLS: true
